### ISSUE TITLE
URDF to GAMMA Format Conversion

### ISSUE THREAD

**Issue by kaitlinflor** [qiaojunyu/GAMMA-ICRA2024#1]
Hi, thank you so much for your contribution to joint estimation! I was wondering – do you have a script that will convert the Sapien dataset in URDF form to the Gamma .npz format?

**Comment by troyehuang** [comment]
i wanna ask this question too, so that i can try more type of object, thanks!

**Comment by qiaojunyu** [comment]
Thank you for your attention. The data conversion has been updated in our code. Please refer to the "data_generation" section.
